name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ main ]

jobs:
  build_and_deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.dde9643d1d753fe31bfed8f5eee30c4f637e4a096106d52968e45f4fda6f4ffd02-ab78c89d-fc7f-45f7-ab89-05a7895ad6d901021110ba012110 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"

          # *** IMPORTANT: tell the action where your files are ***
          app_location: "/"         # your index.html is at the repo root
          api_location: "api"       # your Azure Functions live in /api
          output_location: "/"      # no build output; serve root as-is

          # since you have no frontend build, skip it so Oryx doesn't try
          skip_app_build: true

